# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OTOSCANO
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
timezone:   Europe/Warsaw
locale:     en_us
name:				OTOSCANO
tagline:    'tagline'
rss:        rss feed url


url:                        "http://c33k.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:           toscanorl
github_username:            c33k
disqus:                     c33k # get it on https://disqus.com/admin/
baseurl_posts_img:          '/assets/images/posts/'
baseurl_featured_img:       '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts:        '/assets/javascripts/'
#icon: /assets/img/icon.png #[best 300px X 300px]

# Build settings
markdown: kramdown
highlighter:         rouge
#theme: minima
permalink:           /:title/

metainfo:
  baseurl: "/"

author:
  name:           	 Rafael L. Toscano
  url:            	 http://c33k.github.io
  facebook:          toscanorl
  twitter:           toscanorl
  #google_plus:       username
  linkedin:          rafael-l-toscano-7232aa21
  #dribbble:          username
  pinterest:         toscanorl
  #kiva:              username

#fb_admins:           toscanorl
#fb_appid:            your facebook app id

exclude: [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port: 9001

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
